Helpify_v3/Controllers/CategoryController.cs
using Helpify_v3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Helpify_v3.Adapters;
using Helpify_v3.Adapters.DataAdapters;
using Helpify_v3.Data;

namespace Helpify_v3.Controllers
{
    public class CategoryController : Controller
    {
        //instance of the adapter
        private IProjectListByCategory _adapterLocal;


        public CategoryController()
        {
            _adapterLocal = new ProjectListByCategoryAdapter();
        }


         public CategoryController(ProjectListByCategoryAdapter adapterLocal)
        {
            _adapterLocal = adapterLocal;
        }

        //db cotext
         private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Category
        public ActionResult Automotive(int id)
        {
            ProjectByCategoryVm Avm = new ProjectByCategoryVm();
            Avm = _adapterLocal.GetProjectsByCategory(id);
            
        
            return View(Avm);
        }

        public ActionResult Electronic(int id, string catName)
        {
            ProjectByCategoryVm Evm = new ProjectByCategoryVm();
            
            Evm = _adapterLocal.GetProjectsByCategory(id);

            Evm.PageTitle = catName;

            return View(Evm);
        }

        public ActionResult WoodCraft(int id)
        {
            ProjectByCategoryVm Wvm = new ProjectByCategoryVm();
            Wvm = _adapterLocal.GetProjectsByCategory(id);

            return View(Wvm);
        }

        public ActionResult Household(int id)
        {
            ProjectByCategoryVm Hvm = new ProjectByCategoryVm();
            Hvm = _adapterLocal.GetProjectsByCategory(id);

            return View(Hvm);
        }

        public ActionResult HomeImprovement(int id)
        {
            ProjectByCategoryVm Ivm = new ProjectByCategoryVm();
            Ivm = _adapterLocal.GetProjectsByCategory(id);

            return View(Ivm);
        }

        public ActionResult Computers(int id)
        {
            ProjectByCategoryVm Cvm = new ProjectByCategoryVm();
            Cvm = _adapterLocal.GetProjectsByCategory(id);

            return View(Cvm);
        }

        public ActionResult Create()
        {
            CreateCategoryVM model = new CreateCategoryVM();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(CreateCategoryVM model)
        {
            return View();
        }
    }
}

Helpify_v3/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpify_v3.Data;
using Helpify_v3.Data.Model;
using Helpify_v3.Models;
using Helpify_v3.Adapters;
using Helpify_v3.Adapters.DataAdapters;
using Microsoft.AspNet.Identity;

namespace Helpify_v3.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private IProjectMessagesInterface _adapter;
        private ApplicationDbContext db = new ApplicationDbContext();

        public MessagesController()
        {
            _adapter = new GetMessagesAdapter();
        }

        public MessagesController(GetMessagesAdapter adapter)
        {
            
            _adapter = adapter;
        }

        // GET: Messages
        public ActionResult ProjectMessage(int id)
        {
            MessageListVm Mvm = new MessageListVm();
            Mvm = _adapter.GetMessagesByProject(id);
            

            return View(Mvm);
        }

        // GET: Messages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        public ActionResult Create(int Id)
        {
            
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int Id, [Bind(Include = "MessageId,SenderName,Location,MessageBody")] MessageVm message)
        {
            string userId = User.Identity.GetUserId();

            if (!db.UserProjectLookups.Any(p => p.ProjectId == Id && p.ApplicationUserId == userId))
            {
                ModelState.AddModelError("InvalidProject", new Exception("Invalid Project ID"));
                return View(message);
            }

            if (ModelState.IsValid)
            {
                Message m = new Message
                {
                    Location = message.Location,
                    MessageBody = message.MessageBody,
                    SenderName = message.SenderName
                };

                db.Messages.Add(m);

                //Fetch Project Id for Lookup table
                var MessageLookupItem = new MessageProjectLookup()
                {
                    ProjectId = Id,
                    MessageId = message.MessageId
                };

                db.MessageProjects.Add(MessageLookupItem);
                db.SaveChanges();
                return RedirectToAction("MyProjects", "Home");
            }

            return View(message);
        }

        // GET: Messages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MessageId,SenderName,Location,MessageBody")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Helpify_v3/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpify_v3.Data;
using Helpify_v3.Data.Model;
using Microsoft.AspNet.Identity;

namespace Helpify_v3.Controllers
{
    
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projects
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Category);
            return View(projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        

        // GET: Projects/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,Title,Description,Location,CategoryId")] Project project)
        {
            if (ModelState.IsValid)
            {
                
                db.Projects.Add(project);

                string Uid = User.Identity.GetUserId();
                //fetch the id of the newly created project
                var ProjectLookupItem = new UserProjectLookup()
                {
                    ProjectId = project.ProjectId,
                    ApplicationUserId = Uid

                };

                

                db.UserProjectLookups.Add(ProjectLookupItem);

                db.SaveChanges();

               // "My Projects", "MyProjects",
             //   return RedirectToAction(".../Home/MyProjects");
             return RedirectToAction("MyProjects", "Home");
            }
            //
            


           //NewProject.Title = project.Title;
           //NewProject.Location = project.Location;
           //NewProject.CategoryId = project.CategoryId;
           //NewProject.Description = project.Description;

 
            // save sata to the lookup
            //

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", project.CategoryId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", project.CategoryId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,Title,Description,Location,CategoryId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyProjects", "Home");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", project.CategoryId);
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("MyProjects", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Helpify_v3/Views/Category/Automotive.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Automotive";
}

<h2>Automotive</h2>

<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <h4>@p.Location</h4>
        </div>
    }

</div>

Helpify_v3/Views/Category/Computers.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Computers";
}

<h2>Computers</h2>
<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <h4>@p.Location</h4>
        </div>
    }

</div>

Helpify_v3/Views/Category/Create.cshtml
@model Helpify_v3.Models.CreateCategoryVM

<h2>Create</h2>

@using (Html.BeginForm())
{
    <div>
        <p>@Html.LabelFor(m => m.CategoryName)</p>

    </div>

Helpify_v3/Views/Category/Electronic.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Electronic";
}

<h2>@Model.PageTitle</h2>
<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <div id="postedbyText">@p.UserName</div>
            <h4>@p.Location</h4>
            <div id="homeIllHelpButtonBox">
                <a id="customButtonMed" href="@Url.Action("Create", "Messages", new { Id = p.ProjectId })">I'll Help!</a>
            </div>
            <br />
            <hr />
        </div>
    }
    <br />
    <div>
        <a id="customButtonMed" href="@Url.Action("Index", "Home")">Go Back Home</a>
    </div>
</div>

Helpify_v3/Views/Category/HomeImprovement.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Home Improvement";
}

<h2>Home Improvement</h2>
<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <h4>@p.Location</h4>
        </div>
    }

</div>

Helpify_v3/Views/Category/Household.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Household";
}

<h2>Household</h2>
<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <h4>@p.Location</h4>
        </div>
    }

</div>

Helpify_v3/Views/Category/WoodCraft.cshtml
@model Helpify_v3.Models.ProjectByCategoryVm
@{
    ViewBag.Title = "Woodcraft";
}

<h2>Woodcraft</h2>
<div class="container">
    @foreach (var p in Model.ProjectByCategoryList)
    {
        <div id="projectListItem">
            <a href="@Url.Action("Details", "Projects", new {id = p.ProjectId})"><h3>@p.Title</h3></a>
            <div>@p.Description</div>
            <h4>@p.Location</h4>
        </div>
    }

</div>